name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        app: [springboot-app]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: "prince0127"
          password: "Docker@27."

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./DEVOPS/${{ matrix.app }}
          file: ./DEVOPS/${{ matrix.app }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app }}:latest
